[package]
name = "rs_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_logger_macro = { path = "../rs_logger_macro" }
